import { Book, User } from "@/@types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Jasur Toshmatov",
    username: "jasur_reads",
    city: "Tashkent",
    rating: 4.9,
    booksCount: 23,
    exchangesCount: 18,
    joinedAt: "2023-03-15",
  },
  {
    id: "2",
    name: "Malika Nazarova",
    username: "malika_n",
    city: "Samarkand",
    rating: 4.7,
    booksCount: 15,
    exchangesCount: 12,
    joinedAt: "2023-07-22",
  },
  {
    id: "3",
    name: "Sarvar Rahimov",
    username: "sarvar_r",
    city: "Namangan",
    rating: 4.5,
    booksCount: 9,
    exchangesCount: 7,
    joinedAt: "2024-01-10",
  },
  {
    id: "4",
    name: "Dilnoza Yusupova",
    username: "dilnoza_y",
    city: "Tashkent",
    rating: 4.8,
    booksCount: 17,
    exchangesCount: 14,
    joinedAt: "2023-11-05",
  },
];

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "O'tkan Kunlar",
    author: "Abdulla Qodiriy",
    genre: "Novel",
    language: "Uzbek",
    publishedYear: 1925,
    pages: 384,
    description:
      "A masterpiece of Uzbek literature. The story of Otabek and Kumush's love, set against the backdrop of 19th century Central Asia.",
    condition: "good",
    type: "both",
    price: 25000,
    city: "Tashkent",
    owner: mockUsers[0],
    createdAt: "2025-01-10",
  },
  {
    id: "2",
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-help",
    language: "Uzbek",
    publishedYear: 2018,
    pages: 320,
    description:
      "A practical guide to building good habits and breaking bad ones. Small changes that lead to remarkable results.",
    condition: "good",
    type: "swap",
    city: "Tashkent",
    owner: mockUsers[0],
    createdAt: "2025-01-12",
  },
  {
    id: "3",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    genre: "History",
    language: "Russian",
    publishedYear: 2011,
    pages: 512,
    description:
      "A brief history of humankind. How Homo sapiens came to rule the world and what the future holds.",
    condition: "good",
    type: "sell",
    price: 50000,
    city: "Samarkand",
    owner: mockUsers[1],
    createdAt: "2025-01-14",
  },
  {
    id: "4",
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Novel",
    language: "Uzbek",
    publishedYear: 1988,
    pages: 208,
    description:
      "A magical story about a young shepherd's journey to find his treasure and follow his dreams.",
    condition: "new",
    type: "swap",
    city: "Tashkent",
    owner: mockUsers[0],
    createdAt: "2025-01-15",
  },
  {
    id: "5",
    title: "1984",
    author: "George Orwell",
    genre: "Novel",
    language: "English",
    publishedYear: 1949,
    pages: 328,
    description:
      "A dystopian novel about a totalitarian society where Big Brother watches everyone.",
    condition: "fair",
    type: "both",
    price: 28000,
    city: "Tashkent",
    owner: mockUsers[1],
    createdAt: "2025-01-16",
  },
  {
    id: "6",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    genre: "Novel",
    language: "Uzbek",
    publishedYear: 1943,
    pages: 96,
    description:
      "A poetic tale about a little prince who travels the universe. Written for children but loved by adults.",
    condition: "good",
    type: "swap",
    city: "Namangan",
    owner: mockUsers[2],
    createdAt: "2025-01-17",
  },
  {
    id: "7",
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    genre: "Finance",
    language: "Uzbek",
    publishedYear: 1997,
    pages: 272,
    description:
      "What the rich teach their kids about money that the poor and middle class do not.",
    condition: "good",
    type: "sell",
    price: 45000,
    city: "Tashkent",
    owner: mockUsers[1],
    createdAt: "2025-01-18",
  },
  {
    id: "8",
    title: "Sherlock Holmes",
    author: "Arthur Conan Doyle",
    genre: "Detective",
    language: "Uzbek",
    publishedYear: 1892,
    pages: 448,
    description:
      "A collection of the best adventures of the legendary detective Sherlock Holmes.",
    condition: "good",
    type: "swap",
    city: "Tashkent",
    owner: mockUsers[0],
    createdAt: "2025-01-19",
  },
  {
    id: "9",
    title: "Mehrobdan Chayon",
    author: "Abdulla Qodiriy",
    genre: "Novel",
    language: "Uzbek",
    publishedYear: 1929,
    pages: 296,
    description:
      "A classic Uzbek novel depicting the tragic love story and social struggles of the early 20th century.",
    condition: "fair",
    type: "free",
    city: "Samarkand",
    owner: mockUsers[1],
    createdAt: "2025-01-20",
  },
  {
    id: "10",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    genre: "Psychology",
    language: "Russian",
    publishedYear: 2011,
    pages: 499,
    description:
      "How two systems of thinking shape our judgments and decisions in everyday life.",
    condition: "good",
    type: "both",
    price: 55000,
    city: "Tashkent",
    owner: mockUsers[3],
    createdAt: "2025-01-21",
  },
  {
    id: "11",
    title: "Daftar Hoshiyasida",
    author: "O'tkir Hoshimov",
    genre: "Novel",
    language: "Uzbek",
    publishedYear: 1994,
    pages: 248,
    description:
      "A touching story about life, love, and the human spirit written by one of the greatest Uzbek writers.",
    condition: "good",
    type: "swap",
    city: "Tashkent",
    owner: mockUsers[3],
    createdAt: "2025-01-22",
  },
  {
    id: "12",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    genre: "Finance",
    language: "English",
    publishedYear: 2020,
    pages: 256,
    description:
      "Timeless lessons on wealth, greed, and happiness. How to think about money in a smarter way.",
    condition: "new",
    type: "sell",
    price: 60000,
    city: "Tashkent",
    owner: mockUsers[0],
    createdAt: "2025-01-23",
  },
];

export const GENRES: string[] = [
  "Novel",
  "History",
  "Science",
  "Self-help",
  "Finance",
  "Psychology",
  "Detective",
  "Fantasy",
  "Biography",
  "Children",
  "Poetry",
];

export const LANGUAGES: string[] = ["Uzbek", "Russian", "English", "Other"];

export const CITIES: string[] = [
  "Tashkent",
  "Samarkand",
  "Bukhara",
  "Namangan",
  "Andijan",
  "Fergana",
  "Qarshi",
];

export const CONDITIONS: { value: Book["condition"]; label: string }[] = [
  { value: "new", label: "New" },
  { value: "good", label: "Good" },
  { value: "fair", label: "Fair" },
  { value: "worn", label: "Worn" },
];

export const TYPES: { value: Book["type"]; label: string }[] = [
  { value: "swap", label: "Swap" },
  { value: "sell", label: "Sell" },
  { value: "both", label: "Swap & Sell" },
  { value: "free", label: "Free" },
];
